server:
  port: 4020
spring:
  datasource:
    url: postgresql://localhost:5432/ribd
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate-dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml